"""update users table

Revision ID: 2a12f201a4e4
Revises: 1140c8af12e6
Create Date: 2025-12-18 22:30:25.264766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a12f201a4e4"
down_revision: Union[str, Sequence[str], None] = "1140c8af12e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("foo", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("bar", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "unique_constraint_foo_bar", "users", ["foo", "bar"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_constraint_foo_bar", "users", type_="unique")
    op.drop_column("users", "bar")
    op.drop_column("users", "foo")
    # ### end Alembic commands ###
